const Endpoints = {
  GET_HOME_STARTUPS: "/user/get-startups/",
  GET_DASHBOARD_DATA: "user/get-dashboard-data",
  GET_STARTUPS: "user/get-startups",
  GET_LEADERS: "/strategy/startup/get-team-members",
  GET_STRATEGY_OPTIONS: "strategy/startup/get-strategy-options",
  GET_INVITE: "get-invite-data",
  ACCEPT_INVITE: "accept-invite",
  GET_ALL_MARKETING: "marketing/startup/get-marketing-strategies",
  CREATE_MARKETING_STRATEGY: "marketing/startup/create-marketing",
  SET_SOCIAL_GOALS: "marketing/startup/set-social-goals",
  GET_MARKETING: "marketing/startup/get-marketing",
  GET_RECOMMENDATION: "marketing/startup/get-recommendations",
  CREATE_PRODUCT: "product/startup/create-product/",
  GET_PRODUCTS: "product/startup/get-products",
  GET_PRODUCT: "product/startup/get-products",
  GET_FEATURE: "product/startup/get-feature",
  CREATE_FEATURE: "product/startup/create-feature/",
  REFRESH_PRS: "product/startup/refresh-prs-issues",
  CREATE_RESEARCH_TASK: "research/startup/create-research-task/",
  GET_RESEARCH_MODULE: "research/startup/create-research-task/",
  GET_RESEARCH_CONTENT: "research/startup/get-content",
  COMPLETE_RESEARCH_TASK: "research/startup/research-task",
  RESEARCH_TASK: "research/startup/research-task",
  GET_SINGLE_STRATEGY: "strategy/startup/get-strategy",
  GET_STRATEGIES: "strategy/startup/get-strategies",
  GET_TEAM_MODULE: "team/startup/get-data",
  GET_PEOPLE: "team/get-people",
  CREATE_CONNECTION_REQUEST: "team/send-request/",
  REQUEST_ACTION: "team/request-action",
};

export default Endpoints;
